### ISSUE TITLE
netvfy-agent snap failed to connect under normal user

### ISSUE THREAD

**Issue by qiyunluoxing** [netvfy/netvfy-agent#30]
I installed netvfy snap in ubuntu 20.04, but failed to connect under normal user. I got the error message of "Error setting the interface "netvfy0": Operation not permitted". 

If I run all the commands using "sudo", netvfy-agent can connect. 

I am not sure whether I should report problems with snap build of netvfy here. I am sorry if I cause any inconvenience.

**Comment by mathieujobin** [comment]
you can try this

```
  sudo chmod 666 /dev/net/tun
  sudo setcap cap_net_bind_service,cap_net_admin=ep /usr/bin/netvfy-agent
```

**Comment by mathieujobin** [comment]
I just tested it, although I could swear this worked with a previous version, it does not seems to work anymore. you must be root

FYI I use `systemctl` to connect to my networks automatically.

```
$ cat /etc/systemd/system/multi-user.target.wants/netvfy-agent.service
[Unit]
Description=Netvfy Agent
After=network.target

[Service]
Environment="HOME=/root"
ExecStart=/usr/bin/netvfy-agent -c networkname
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by nicboul** [comment]
snap doesn't support changing the capabilities on the binary  (last time I checked) , you have to run it as root

**Comment by qiyunluoxing** [comment]
Thank you for your advice.
